################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 1.7
##  \   \         Application : Virtex-5 FPGA GTX Transceiver Wizard
##  /   /         Filename : implement_synplify_sh.ejava 
## /___/   /\     Timestamp :
## \   \  /  \
##  \___\/\___\
##
##
## implement_synplify.sh script 
## Generated by Xilinx GTX Transceiver Wizard
##

#!/bin/bash
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the wizard
#-----------------------------------------------------------------------------

##---------------------Change CWD to results-------------------------------------

#Clean results directory
#Create results directory
#Change current directory to results
echo "WARNING: Removing existing results directory"
rm -rf results
mkdir results
cp synplify.prj   ./results
cp *.ngc          ./results

##-----------------------------Run Synthesis-------------------------------------

echo "### Running Synplify Pro - "
synplify_pro -batch synplify.prj

cp gtx_top.edf ./results
cd ./results

##-------------------------------Run ngdbuild---------------------------------------

echo 'Running ngdbuild'
ngdbuild -uc ../../example_design/gtx_top.ucf -p xc5vfx70t-ff1136-1 gtx_top.edf gtx_top.ngd

#end run ngdbuild section

##-------------------------------Run map-------------------------------------------

echo 'Running map'
map -p xc5vfx70t-ff1136-1 -o mapped.ncd gtx_top.ngd

##-------------------------------Run par-------------------------------------------

echo 'Running par'
par mapped.ncd routed.ncd

##---------------------------Report par results-------------------------------------

echo 'Running design through bitgen'
bitgen -w routed.ncd

##-------------------------------Trace Report---------------------------------------

echo 'Running trce'
trce -e 10 routed.ncd mapped.pcf -o routed 

##-------------------------------Run netgen------------------------------------------

echo 'Running netgen to create gate level VHDL model'
netgen -ofmt vhdl -sim -dir . -tm gtx_top -w routed.ncd routed.vhd

#Change directory to implement

cd ..

