   
################################################################################
##$Date: 2010/02/16 10:19:59 $
##$Revision: 1.6 $
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /
## \   \   \/     Vendor: Xilinx
##  \   \         Version : 1.7
##  /   /         Application : GTX Transceiver Wizard
## /___/   /\     Filename : simulate_isim.sh
## \   \  /  \
##  \___\/\___\
##
##
## Script SIMULATE_ISIM.SH
## Generated by Xilinx GTX Transceiver Wizard


##***************************** Beginning of Script ***************************
        

## Create and map work directory
mkdir work


##MGT Wrapper
vhpcomp -work work  ../../../gtx_tile.vhd;
vhpcomp -work work  ../../../gtx.vhd;




##Example Design modules
vhpcomp -work work  ../../example_design/frame_gen.vhd;
vhpcomp -work work  ../../example_design/frame_check.vhd;
vhpcomp -work work  ../../example_design/gtx_top.vhd;
vhpcomp -work work  ../demo_tb.vhd;

##Other modules
vhpcomp -work work ../sim_reset_mgt_model.vhd;

##Load Design
fuse work.DEMO_TB -L unisim -L secureip -o demo_tb.exe

./demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim  


